project:
  type: default
  output-dir: _site

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true
    code-tools: true
    css: styles.css

bibliography: docs/references.bib
csl: https://www.zotero.org/styles/ieee
link-citations: true
