project:
  type: website
  output-dir: _site
  render: 
    - index.qmd
  resources:
    - /docs/images  
website:
  favicon: logo-teal.svg
  open-graph: true
  site-url: https://www.mcguirerobotics.com/px4_sim_research_report/
  navbar:
    background: "#27788b"
    search: true
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "Preperations"
        href: "#survey-preparation"
      - text: "Results"
        href: "#survey-results"
      - text: "Discussion"
        href: "#brief-discussion-and-recommendation"
      - text: "Appendix"
        href: "#sec-pilot"

