[project]
name = "research_reports"
description = "Research reports generator"
authors = ["kimbe <kimbe@example.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]

[dependencies]
python = ">=3.8"
requests = "*"
beautifulsoup4 = "*"
mkdocs-bibtex = ">=4.4.0,<5"
pypandoc = ">=1.15,<2"
mkdocs-material = ">=9.6.20,<10"

[pypi-dependencies]
mkdocs-print-site-plugin = ">=2.8, <3"
